### ISSUE TITLE
How  circumference is calculated/measured

### ISSUE THREAD

**Issue by farazBhatti** [measure-me/measure-me-demo#9]
Hi Prasad, you have mentioned how lengths can be calculated using AR, but it seems there is no information regarding calculation of circumference for example 
Head circumference
Waist circumference
Mid-arm circumference

would it be possible for you to also share this information. Thanks

**Comment by Liies** [comment]
up

**Comment by prasad-kumkar** [comment]
Circumference will be measured when the app captures images from front and side, then calculating distance and angles. After which we can calculate the circumference.

**Comment by prasad-kumkar** [comment]
Sorry for the delayed reply @farazBhatti @Liies. I have just started working on the js library. Please feel free to contact me ([LinkedIn](https://www.linkedin.com/in/prasad-kumkar/) or prasadkumkar111@gmail.com) 😃. I am looking for contributors for this project
